package GUI;
import javax.swing.*;

import java.io.File;
import java.io.IOException;

import javax.swing.JPanel;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

import Logic.Logic;

/**
 *
 * @author proxc
 */
public class Home extends javax.swing.JFrame {
 public static String filepath;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Blue_Ribbon = new javax.swing.JPanel();
        smvec = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TTG_logo = new javax.swing.JLabel();
        TTG_Text = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Staffs_button = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Classes_button = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Update_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Generate_button = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Blue_Ribbon.setBackground(new java.awt.Color(0, 34, 73));
        Blue_Ribbon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Blue_RibbonMouseDragged(evt);
            }
        });
        Blue_Ribbon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Blue_RibbonMousePressed(evt);
            }
        });
        Blue_Ribbon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        smvec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        smvec.setForeground(new java.awt.Color(255, 255, 255));
        smvec.setText("SRI MANAKULA VINAYAGAR ENGINEERING COLLEGE");
        Blue_Ribbon.add(smvec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 330, 30));

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        Blue_Ribbon.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));
        Blue_Ribbon.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 348, -1));

        TTG_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/TimeTable.png")));
        Blue_Ribbon.add(TTG_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 60));

        TTG_Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TTG_Text.setForeground(new java.awt.Color(45, 118, 232));
        TTG_Text.setText("TIME TABLE GENERATOR");
        TTG_Text.setMaximumSize(new java.awt.Dimension(125, 15));
        Blue_Ribbon.add(TTG_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 390, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("College Management");
        Blue_Ribbon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 20));

        jPanel1.add(Blue_Ribbon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 200));

        Staffs_button.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        Staffs_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Staffs_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Staffs_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Staffs_buttonMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setText("STAFFS");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/group_52px.png"))); // NOI18N

        javax.swing.GroupLayout Staffs_buttonLayout = new javax.swing.GroupLayout(Staffs_button);
        Staffs_button.setLayout(Staffs_buttonLayout);
        Staffs_buttonLayout.setHorizontalGroup(
            Staffs_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staffs_buttonLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(Staffs_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        Staffs_buttonLayout.setVerticalGroup(
            Staffs_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staffs_buttonLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(Staffs_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 140, 120));

        Classes_button.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        Classes_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Classes_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Classes_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Classes_buttonMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 118, 232));
        jLabel17.setText("CLASSES");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/list_64px.png"))); // NOI18N

        javax.swing.GroupLayout Classes_buttonLayout = new javax.swing.GroupLayout(Classes_button);
        Classes_button.setLayout(Classes_buttonLayout);
        Classes_buttonLayout.setHorizontalGroup(
            Classes_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Classes_buttonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Classes_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Classes_buttonLayout.setVerticalGroup(
            Classes_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Classes_buttonLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel1.add(Classes_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 140, 120));

        Update_button.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        Update_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Update_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Update_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Update_buttonMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("UPDATE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/download_52px.png"))); // NOI18N

        javax.swing.GroupLayout Update_buttonLayout = new javax.swing.GroupLayout(Update_button);
        Update_button.setLayout(Update_buttonLayout);
        Update_buttonLayout.setHorizontalGroup(
            Update_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_buttonLayout.createSequentialGroup()
                .addGroup(Update_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Update_buttonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Update_buttonLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Update_buttonLayout.setVerticalGroup(
            Update_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_buttonLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(Update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 140, 120));

        Generate_button.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        Generate_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Generate_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Generate_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try {
                    Generate_buttonMousePressed(evt);
                } catch (Exception e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 118, 232));
        jLabel19.setText("GENERATE");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/settings_48px.png")));

        javax.swing.GroupLayout Generate_buttonLayout = new javax.swing.GroupLayout(Generate_button);
        Generate_button.setLayout(Generate_buttonLayout);
        Generate_buttonLayout.setHorizontalGroup(
            Generate_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Generate_buttonLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(180, 180, 180))
        );
        Generate_buttonLayout.setVerticalGroup(
            Generate_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(Generate_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Generate_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 490, 50));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 153));
        kGradientPanel1.setkGradientFocus(700);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    
    
    
    int xx,xy;
    public void Generate_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_buttonMouseEntered
        // TODO add your handling code here:
        setColor(Generate_button);
    }//GEN-LAST:event_Generate_buttonMouseEntered

    public void Generate_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generate_buttonMouseExited
        // TODO add your handling code here:
        resetColor(Generate_button);
    }//GEN-LAST:event_Generate_buttonMouseExited

    public void Staffs_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staffs_buttonMousePressed
        // TODO add your handling code here:
        new Staffs().show();
        //just a sample.
        
    }//GEN-LAST:event_Staffs_buttonMousePressed

    public void Staffs_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staffs_buttonMouseExited
        // TODO add your handling code here:
        resetColor(Staffs_button);
    }//GEN-LAST:event_Staffs_buttonMouseExited

    public void Staffs_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staffs_buttonMouseEntered
        // TODO add your handling code here:
        setColor(Staffs_button);
    }//GEN-LAST:event_Staffs_buttonMouseEntered

    public void Classes_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Classes_buttonMouseEntered
        // TODO add your handling code here:
        setColor(Classes_button);
    }//GEN-LAST:event_Classes_buttonMouseEntered

    public void Classes_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Classes_buttonMouseExited
        // TODO add your handling code here:
        resetColor(Classes_button);
    }//GEN-LAST:event_Classes_buttonMouseExited

    public void Blue_RibbonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blue_RibbonMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Blue_RibbonMousePressed

    public void Blue_RibbonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Blue_RibbonMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_Blue_RibbonMouseDragged

    public void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    public void Update_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_buttonMouseEntered
        // TODO add your handling code here:
        setColor(Update_button);
    }//GEN-LAST:event_Update_buttonMouseEntered

    public void Update_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_buttonMouseExited
        // TODO add your handling code here:
        resetColor(Update_button);
    }//GEN-LAST:event_Update_buttonMouseExited

    public String Update_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_buttonMousePressed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        int i = filechooser.showOpenDialog(Update_button);
        if(i==JFileChooser.APPROVE_OPTION){
        File fc = filechooser.getSelectedFile();
        filepath = fc.getAbsolutePath(); 
        return filepath;
        }
        return null;
    }//GEN-LAST:event_Update_buttonMousePressed

    public void Classes_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Classes_buttonMousePressed
        // TODO add your handling code here:
       new Classes().show();
    }//GEN-LAST:event_Classes_buttonMousePressed

    public void Generate_buttonMousePressed(java.awt.event.MouseEvent evt) throws Exception {//GEN-FIRST:event_Generate_buttonMousePressed
        // TODO add your handling code here:
        if(filepath.isEmpty()) Update_buttonMousePressed(evt);
        else{
        try {
            Logic.main(null);
        } catch (InvalidFormatException | IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_Generate_buttonMousePressed
 public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Blue_Ribbon;
    public javax.swing.JPanel Classes_button;
    public javax.swing.JPanel Generate_button;
    public javax.swing.JPanel Staffs_button;
    public javax.swing.JLabel TTG_Text;
    public javax.swing.JLabel TTG_logo;
    public javax.swing.JPanel Update_button;
    public javax.swing.JLabel exit;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JSeparator jSeparator1;
    public keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JLabel smvec;
    // End of variables declaration//GEN-END:variables
}
