/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author niran
 */
public class Staffs extends javax.swing.JFrame {

    /**
     * Creates new form Staffs
     */
    public Staffs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   public void initComponents() {

        Staffs_Blue_Ribbon = new javax.swing.JPanel();
        Staffs_logo = new javax.swing.JLabel();
        Staffs_Text = new javax.swing.JLabel();
        Staffs_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Staffs_Blue_Ribbon.setBackground(new java.awt.Color(0, 34, 73));
        Staffs_Blue_Ribbon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Staffs_Blue_RibbonMouseDragged(evt);
            }
        });
        Staffs_Blue_Ribbon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Staffs_Blue_RibbonMousePressed(evt);
            }
        });
        Staffs_Blue_Ribbon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Staffs_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/group_52px_1.png")));
        Staffs_Blue_Ribbon.add(Staffs_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 60));

        Staffs_Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Staffs_Text.setForeground(new java.awt.Color(45, 118, 232));
        Staffs_Text.setText("STAFFS");
        Staffs_Text.setMaximumSize(new java.awt.Dimension(125, 15));
        Staffs_Blue_Ribbon.add(Staffs_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 390, 40));

        Staffs_Table.setLayout(null);
      
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1st Period", "2nd Period", "3rd Period", "4th Period", "5th Period", "6th Period", "7th Period", "8th Period"
            }
        ));
    

        jScrollPane1.setViewportView(jTable1);
        
        Staffs_Table.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1080, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Staffs_Blue_Ribbon, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
            .addComponent(Staffs_Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Staffs_Blue_Ribbon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staffs_Table, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Staffs_Blue_RibbonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staffs_Blue_RibbonMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_Staffs_Blue_RibbonMouseDragged

    public void Staffs_Blue_RibbonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staffs_Blue_RibbonMousePressed
;
    }//GEN-LAST:event_Staffs_Blue_RibbonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staffs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staffs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JPanel Staffs_Blue_Ribbon;
   public javax.swing.JPanel Staffs_Table;
   public javax.swing.JLabel Staffs_Text;
    public javax.swing.JLabel Staffs_logo;
   public javax.swing.JScrollPane jScrollPane1;
   public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
